default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: awesome_events_development
test:
  <<: *default
  database: awesome_events_test
production:
  <<: *default
  database: awesome_events
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  password: <%= ENV['AWESOME-EVENTS_DATABASE_PASSWORD'] %>
