defaults: &defaults

development:
  <<: *defaults
  twitter:
    url: 'https://twitter.com/'
    consumer_key: <%= ENV["TWITTER_API_KEY"]%>
    consumer_secret: <%= ENV["TWITTER_API_SECRET"]%>

test:
  <<: *defaults

production:
  <<: *defaults
